# Generated by Django 4.0.3 on 2022-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('division', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('reg_no', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
