# Generated by Django 4.0.3 on 2022-04-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
