# Generated by Django 4.0.3 on 2022-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_book_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_books',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='max_assignable',
            field=models.IntegerField(default=2),
        ),
    ]
